version: '3.8'

services:
  mysql:
    image: mysql:8
    container_name: courier-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: courier-tracking
      MYSQL_USER: courier
      MYSQL_PASSWORD: courier
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -uroot -proot"]
      interval: 10s
      timeout: 5s
      retries: 5

  app:
    build: .
    container_name: courier-app
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/courier-tracking
      SPRING_DATASOURCE_USERNAME: courier
      SPRING_DATASOURCE_PASSWORD: courier
      SPRING_PROFILES_ACTIVE: docker
    depends_on:
      mysql:
        condition: service_healthy

volumes:
  mysql_data:
